### ISSUE TITLE
The custom field multi select appears in courses but not in user

### ISSUE THREAD

**Issue by paulrm** [call-learning/moodle-customfield_multiselect#2]
In courses works perfectly, bur in user profile

![MooTest-Administration-Users-Accounts-User-profile-fields](https://user-images.githubusercontent.com/962154/96673236-6f3a7680-133c-11eb-904d-838e20ccbfad.png)

**Comment by laurentdavid** [comment]
Hi Paul,

If I understand correctly you are pointing out that it does not appear in the list of possible user profiles fields. This is unfortunately the case as the new 3.7 custom fields are not the same as the user profile fields so if you add a new custom field type, this will only add it to courses as they are the only entity for now that uses the new custom field. 
I suppose one day it will be completely unified, but for now user profiles fields and custom fields are completely separate concepts (and code).

Laurent

**Comment by laurentdavid** [comment]
I leave the issue open for now if it was a misunderstanding from my side.

**Comment by paulrm** [comment]
Thanks @laurentdavid for you fast response.
You understand fine, I will try to fork and develop to 3.9

Best Regards, Paul
